import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { themeToCss } from "@velloo/renderer";
import { neutralizeCssText, type Theme } from "@velloo/schema";
import { diffFile } from "../diff.ts";
import { emitDtcgFile } from "./dtcg.ts";
import type { EmitThemeFile, EmitThemeResult } from "./index.ts";

export interface EmitCssVariablesOptions {
  outputDir: string;
  /** Stylesheet location relative to `outputDir`. Default `velloo-theme.css`. */
  cssPath?: string | undefined;
  /** Folder custom.css contents — appended after the variables. */
  customCss?: string | undefined;
  apply?: boolean | undefined;
}

/**
 * The theme for an app with no CSS framework: the exact custom properties the
 * canvas injects (`themeToCss`), so the `var(--…)` references in emitted inline
 * styles resolve to the same values in the app. No Tailwind, no build step.
 */
export async function emitCssVariables(
  theme: Theme,
  options: EmitCssVariablesOptions,
): Promise<EmitThemeResult> {
  const path = join(options.outputDir, options.cssPath ?? "velloo-theme.css");
  const custom = options.customCss?.trim() ? `\n\n${neutralizeCssText(options.customCss)}` : "";
  const contents = `/* Generated by velloo emit_theme — the design's theme as CSS custom properties. */\n${themeToCss(theme)}${custom}\n`;
  const diff = await diffFile(path, contents);
  let applied = false;
  if (options.apply && !diff.identical) {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, "utf8");
    applied = true;
  }
  const files: EmitThemeFile[] = [{ path, contents, diff, applied }];
  const dtcg = await emitDtcgFile(theme, options);
  files.push(dtcg.file);
  return {
    files,
    warnings: dtcg.warnings,
    notes: [
      `Link ${options.cssPath ?? "velloo-theme.css"} from the app's base layout (before its own stylesheets) so inline var(--…) references resolve. A \`.dark\` ancestor switches the dark palette.`,
    ],
  };
}
