import type { ColorPair, Colors, Theme } from "@velloo/schema";

/**
 * Map theme color slots to shadcn's --color-* CSS variable convention.
 * Mirrors @velloo/renderer's `theme-to-css.ts` so what the canvas shows is
 * exactly what the user gets after export.
 */
const COLOR_SLOTS: Array<{ key: keyof Colors; pair: boolean }> = [
  { key: "background", pair: false },
  { key: "foreground", pair: false },
  { key: "primary", pair: true },
  { key: "secondary", pair: true },
  { key: "muted", pair: true },
  { key: "accent", pair: true },
  { key: "destructive", pair: true },
  { key: "card", pair: true },
  { key: "popover", pair: true },
  { key: "border", pair: false },
  { key: "input", pair: false },
  { key: "ring", pair: false },
];

function defaultOf(value: ColorPair | undefined): string | undefined {
  if (typeof value === "string") return value;
  if (value) return value.DEFAULT;
  return undefined;
}

function fgOf(value: ColorPair | undefined): string | undefined {
  if (value && typeof value === "object") return value.foreground;
  return undefined;
}

function appendColorBlock(colors: Partial<Colors>, lines: string[]): void {
  for (const { key, pair } of COLOR_SLOTS) {
    const value = colors[key];
    if (value === undefined) continue;
    const def = defaultOf(value);
    if (def !== undefined) lines.push(`  --color-${key}: ${def};`);
    if (pair) {
      const fg = fgOf(value);
      if (fg !== undefined) lines.push(`  --color-${key}-foreground: ${fg};`);
    }
  }
}

export interface GlobalsCssOptions {
  /** Emit `/* TODO: load this font ... *​/` next to --font-sans. Default true. */
  fontLoadingNote?: boolean;
  /** Folder custom.css contents to append verbatim at the end. */
  customCss?: string;
}

export function emitGlobalsCss(theme: Theme, opts: GlobalsCssOptions = {}): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Generated by velloo from theme "${theme.name}".`);
  lines.push(` * Hand-edits are welcome; re-running \`velloo theme:export\` shows a diff.`);
  lines.push(` */`);
  // @import rules must precede everything else in the sheet.
  const googleFonts = theme.typography.googleFonts;
  if (googleFonts && googleFonts.length > 0) {
    const families = googleFonts.map((f) => `family=${f.replace(/ /g, "+")}`).join("&");
    lines.push(`@import url("https://fonts.googleapis.com/css2?${families}&display=swap");`);
  }
  lines.push(`@import "tailwindcss";`);
  lines.push("");
  lines.push(`@theme {`);

  // Radius.
  const radiusBase = theme.radius.md ?? theme.radius.lg ?? theme.radius.sm;
  if (radiusBase !== undefined) {
    const v = typeof radiusBase === "number" ? `${radiusBase}px` : radiusBase;
    lines.push(`  --radius: ${v};`);
  }

  // Typography: every declared role becomes a --font-<role> token, which
  // Tailwind v4 surfaces as a `font-<role>` utility.
  const fonts = theme.typography.fontFamily;
  if (fonts) {
    let noteEmitted = false;
    for (const [role, stack] of Object.entries(fonts)) {
      lines.push(`  --font-${role}: ${stack};`);
      if (
        !noteEmitted &&
        opts.fontLoadingNote !== false &&
        (!googleFonts || googleFonts.length === 0)
      ) {
        lines.push(`  /* TODO: load these fonts via next/font or a <link> in your <head>. */`);
        noteEmitted = true;
      }
    }
  }

  appendColorBlock(theme.colors, lines);

  lines.push(`}`);
  lines.push("");

  // Dark-mode overrides. shadcn convention: a `.dark` class on <html> or <body>
  // re-points the --color-* tokens. We emit one block keyed off `.dark` so users
  // can hook it up to any framework's dark-mode toggle (Tailwind v4 darkVariant
  // defaults to `prefers-color-scheme`; most apps swap to a class-based variant
  // via `@custom-variant dark (&:is(.dark *))` in their globals.css).
  if (theme.colorsDark) {
    lines.push(`@custom-variant dark (&:is(.dark *));`);
    lines.push("");
    lines.push(`.dark {`);
    appendColorBlock(theme.colorsDark, lines);
    lines.push(`}`);
    lines.push("");
  }

  lines.push(`@layer base {`);
  lines.push(`  * {`);
  lines.push(`    border-color: var(--color-border);`);
  lines.push(`  }`);
  lines.push(`  body {`);
  lines.push(`    background-color: var(--color-background);`);
  lines.push(`    color: var(--color-foreground);`);
  lines.push(`    font-family: var(--font-sans);`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");

  if (opts.customCss && opts.customCss.trim() !== "") {
    lines.push(`/* === velloo theme/custom.css === */`);
    lines.push(opts.customCss.trimEnd());
    lines.push("");
  }

  return lines.join("\n");
}
