import type { ColorPair, Theme } from "@velloo/schema";

/**
 * Map theme color slots to shadcn's --color-* CSS variable convention.
 * Mirrors @velloo/renderer's `theme-to-css.ts` so what the canvas shows is
 * exactly what the user gets after export.
 */
const COLOR_SLOTS: Array<{ key: keyof Theme["colors"]; pair: boolean }> = [
  { key: "background", pair: false },
  { key: "foreground", pair: false },
  { key: "primary", pair: true },
  { key: "secondary", pair: true },
  { key: "muted", pair: true },
  { key: "accent", pair: true },
  { key: "destructive", pair: true },
  { key: "card", pair: true },
  { key: "popover", pair: true },
  { key: "border", pair: false },
  { key: "input", pair: false },
  { key: "ring", pair: false },
];

function defaultOf(value: ColorPair | string | undefined): string | undefined {
  if (typeof value === "string") return value;
  if (value && typeof value === "object") return value.DEFAULT;
  return undefined;
}

function fgOf(value: ColorPair | string | undefined): string | undefined {
  if (value && typeof value === "object") return value.foreground;
  return undefined;
}

export interface GlobalsCssOptions {
  /** Emit `/* TODO: load this font ... *​/` next to --font-sans. Default true. */
  fontLoadingNote?: boolean;
}

export function emitGlobalsCss(theme: Theme, opts: GlobalsCssOptions = {}): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Generated by velloo from theme "${theme.name}".`);
  lines.push(` * Hand-edits are welcome; re-running \`velloo theme:export\` shows a diff.`);
  lines.push(` */`);
  lines.push(`@import "tailwindcss";`);
  lines.push("");
  lines.push(`@theme {`);

  // Radius.
  const radius = (theme.radius ?? {}) as Record<string, unknown>;
  const radiusBase = radius.md ?? radius.lg ?? radius.sm;
  if (radiusBase !== undefined) {
    const v = typeof radiusBase === "number" ? `${radiusBase}px` : String(radiusBase);
    lines.push(`  --radius: ${v};`);
  }

  // Typography: fonts.
  const typography = (theme.typography ?? {}) as Record<string, unknown>;
  const fonts = typography.fontFamily as Record<string, unknown> | undefined;
  if (fonts?.sans !== undefined) {
    lines.push(`  --font-sans: ${fonts.sans};`);
    if (opts.fontLoadingNote !== false) {
      lines.push(`  /* TODO: load this font via next/font or a <link> in your <head>. */`);
    }
  }
  if (fonts?.mono !== undefined) {
    lines.push(`  --font-mono: ${fonts.mono};`);
  }

  // Colors.
  const colors = theme.colors as Record<string, ColorPair | string | undefined>;
  for (const { key, pair } of COLOR_SLOTS) {
    const value = colors[key];
    if (value === undefined) continue;
    const def = defaultOf(value);
    if (def !== undefined) lines.push(`  --color-${key}: ${def};`);
    if (pair) {
      const fg = fgOf(value);
      if (fg !== undefined) lines.push(`  --color-${key}-foreground: ${fg};`);
    }
  }

  lines.push(`}`);
  lines.push("");
  lines.push(`@layer base {`);
  lines.push(`  * {`);
  lines.push(`    border-color: var(--color-border);`);
  lines.push(`  }`);
  lines.push(`  body {`);
  lines.push(`    background-color: var(--color-background);`);
  lines.push(`    color: var(--color-foreground);`);
  lines.push(`    font-family: var(--font-sans);`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");

  return lines.join("\n");
}
