import {
  type ColorPair,
  type Colors,
  type ColorsOverride,
  sanitizeCssTokenValue as cssv,
  isCssIdent,
  neutralizeCssText,
  sanitizeGoogleFontSpec,
  type Theme,
  typesetCss,
  typesetSafelist,
  typesetThemeTokens,
} from "@velloo/schema";

/** The typeset sheet's filename, a sibling of the emitted globals.css. */
export const TYPESET_CSS_FILENAME = "typeset.css";

/**
 * The typeset stylesheet as its own file — the same generator the canvas
 * renders with, so a design and the app it exports to cannot drift.
 *
 * A separate file rather than a block inside globals.css because typography is
 * the thing users most want to hand-tune, and a standalone sheet is reviewable
 * and overridable on its own. Re-running the export diffs it like any other
 * generated artifact.
 */
export function emitTypesetCss(theme: Theme): string {
  return [
    "/**",
    ` * Generated by velloo from theme "${cssv(theme.name)}".`,
    " *",
    " * Typography derived from the theme's typesets. Three controls per typeset —",
    " * size, leading, flow — and the ladder below derives from them. Add `typeset`",
    " * to a container to style everything inside it; add `typeset-<name>` for a",
    " * different rhythm. Every rule has zero specificity, so your own utilities",
    " * and inline styles always win.",
    " */",
    "",
    typesetCss(theme.typography.typesets),
    "",
  ].join("\n");
}

/**
 * Map theme color slots to shadcn's --color-* CSS variable convention.
 * Mirrors @velloo/renderer's `theme-to-css.ts` so what the canvas shows is
 * exactly what the user gets after export. Exported so `import-theme` parses
 * exactly the vocabulary this module emits (round-trip symmetry).
 */
export const COLOR_SLOTS: Array<{ key: keyof Colors; pair: boolean }> = [
  { key: "background", pair: false },
  { key: "foreground", pair: false },
  { key: "primary", pair: true },
  { key: "secondary", pair: true },
  { key: "muted", pair: true },
  { key: "accent", pair: true },
  { key: "destructive", pair: true },
  { key: "card", pair: true },
  { key: "popover", pair: true },
  { key: "border", pair: false },
  { key: "input", pair: false },
  { key: "ring", pair: false },
];

/**
 * The var names the semantic slots own (plus their `-foreground` pairs). The
 * import path keeps these out of `palette` (see `paletteName`), and the emit
 * path skips palette entries that collide — a `palette.muted` would otherwise
 * emit a SECOND `--color-muted` that wins in light mode while `.dark`
 * re-points the same var at the semantic dark surface, turning `text-muted`
 * body copy invisible on brand surfaces.
 */
export const SEMANTIC_SLOTS: ReadonlySet<string> = new Set<string>(
  COLOR_SLOTS.flatMap(({ key, pair }) =>
    pair ? [key as string, `${key as string}-foreground`] : [key as string],
  ),
);

/** Palette keys (light + dark) that shadow a semantic slot — skipped on emit. */
export function paletteShadowedSlots(theme: Theme): string[] {
  const names = new Set<string>();
  for (const source of [theme.palette, theme.paletteDark]) {
    for (const name of Object.keys(source ?? {})) {
      if (SEMANTIC_SLOTS.has(name)) names.add(name);
    }
  }
  return [...names].sort();
}

function defaultOf(value: ColorPair | undefined): string | undefined {
  if (typeof value === "string") return value;
  if (value) return value.DEFAULT;
  return undefined;
}

function fgOf(value: ColorPair | undefined): string | undefined {
  if (value && typeof value === "object") return value.foreground;
  return undefined;
}

/** Raw scale/role passthrough: `primary-600` → `--color-primary-600`. */
function appendPalette(palette: Record<string, string> | undefined, lines: string[]): void {
  if (!palette) return;
  for (const [name, value] of Object.entries(palette)) {
    if (!isCssIdent(name)) continue;
    if (SEMANTIC_SLOTS.has(name)) {
      lines.push(
        `  /* palette.${name} skipped: it would shadow the semantic --color-${name} (set colors.${name} instead, or rename the palette token). */`,
      );
      continue;
    }
    lines.push(`  --color-${name}: ${cssv(value)};`);
  }
}

/** Named spacing tokens: `icon-rail` → `--spacing-icon-rail`, surfaced as `w-icon-rail`/`p-icon-rail`/… */
function appendSpacing(spacing: Theme["spacing"], lines: string[]): void {
  if (!spacing) return;
  for (const [name, value] of Object.entries(spacing)) {
    // Skip the numeric Tailwind scale (0/1/2/…) — it's built in and unitless;
    // only named tokens need a `--spacing-*` so `w-icon-rail` resolves.
    if (!Number.isNaN(Number(name))) continue;
    if (!isCssIdent(name)) continue;
    if (typeof value === "string" || typeof value === "number") {
      lines.push(`  --spacing-${name}: ${cssv(String(value))};`);
    }
  }
}

/** Named box-shadows: `card` → `--shadow-card`, surfaced as `shadow-card`. */
function appendShadows(shadows: Theme["shadows"], lines: string[]): void {
  if (!shadows) return;
  for (const [name, value] of Object.entries(shadows)) {
    if (!isCssIdent(name)) continue;
    if (typeof value === "string" || typeof value === "number") {
      lines.push(`  --shadow-${name}: ${cssv(String(value))};`);
    }
  }
}

/**
 * Render captured `@keyframes` to CSS text — one block per name. Tailwind v4
 * resolves `--animate-<name>` against keyframes defined inside `@theme`, so
 * this is emitted there (and into the JIT's `@theme` for canvas compilation).
 */
/** A keyframe step selector: `from`/`to`/`50%` — no braces/semicolons/angles. */
function safeKeyframeSelector(selector: string): string {
  return selector.replace(/[^A-Za-z0-9%.,\s]/g, "").trim();
}

export function keyframesToCss(keyframes: Theme["keyframes"], indent = ""): string {
  if (!keyframes) return "";
  const blocks: string[] = [];
  for (const [name, steps] of Object.entries(keyframes)) {
    if (!isCssIdent(name)) continue;
    const stepLines = Object.entries(steps).map(([selector, decls]) => {
      const body = Object.entries(decls)
        .filter(([prop]) => isCssIdent(prop))
        .map(([prop, value]) => `${prop}: ${cssv(String(value))}`)
        .join("; ");
      return `${indent}  ${safeKeyframeSelector(selector)} { ${body}; }`;
    });
    blocks.push(`${indent}@keyframes ${name} {\n${stepLines.join("\n")}\n${indent}}`);
  }
  return blocks.join("\n");
}

/** `--animate-<name>` lines for the animation shorthands (drive `animate-<name>`). */
function appendAnimations(animation: Theme["animation"], lines: string[]): void {
  if (!animation) return;
  for (const [name, value] of Object.entries(animation)) {
    if (!isCssIdent(name)) continue;
    lines.push(`  --animate-${name}: ${cssv(value)};`);
  }
}

function appendColorBlock(colors: ColorsOverride, lines: string[]): void {
  for (const { key, pair } of COLOR_SLOTS) {
    const value = colors[key];
    if (value === undefined) continue;
    const def = defaultOf(value);
    if (def !== undefined) lines.push(`  --color-${key}: ${cssv(def)};`);
    if (pair) {
      const fg = fgOf(value);
      if (fg !== undefined) lines.push(`  --color-${key}-foreground: ${cssv(fg)};`);
    }
  }
}

export interface GlobalsCssOptions {
  /** Emit `/* TODO: load this font ... *​/` next to --font-sans. Default true. */
  fontLoadingNote?: boolean | undefined;
  /** Folder custom.css contents to append verbatim at the end. */
  customCss?: string | undefined;
}

export function emitGlobalsCss(theme: Theme, opts: GlobalsCssOptions = {}): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Generated by velloo from theme "${cssv(theme.name)}".`);
  lines.push(` * Hand-edits are welcome; re-running \`velloo theme export\` shows a diff.`);
  lines.push(` */`);
  // @import rules must precede everything else in the sheet.
  const googleFonts = theme.typography.googleFonts;
  if (googleFonts && googleFonts.length > 0) {
    const families = googleFonts.map((f) => `family=${sanitizeGoogleFontSpec(f)}`).join("&");
    lines.push(`@import url("https://fonts.googleapis.com/css2?${families}&display=swap");`);
  }
  lines.push(`@import "tailwindcss";`);
  // The typeset sheet re-declares the derived --text-*/--leading-*/--tracking-*
  // tokens the @theme block below seeds, so it must be imported after Tailwind.
  lines.push(`@import "./${TYPESET_CSS_FILENAME}";`);
  lines.push("");
  // The typeset ladder's class literals live in @velloo/schema rather than in a
  // scanned component file, so safelist them or `text-h1` never compiles.
  for (const pattern of typesetSafelist()) {
    lines.push(`@source inline("${pattern}");`);
  }
  lines.push("");
  lines.push(`@theme {`);

  // Radius.
  const radiusBase = theme.radius.md ?? theme.radius.lg ?? theme.radius.sm;
  if (radiusBase !== undefined) {
    const v = typeof radiusBase === "number" ? `${radiusBase}px` : cssv(radiusBase);
    lines.push(`  --radius: ${v};`);
  }

  // Typography: every declared role becomes a --font-<role> token, which
  // Tailwind v4 surfaces as a `font-<role>` utility.
  const fonts = theme.typography.fontFamily;
  if (fonts) {
    let noteEmitted = false;
    for (const [role, stack] of Object.entries(fonts)) {
      if (!isCssIdent(role)) continue;
      lines.push(`  --font-${role}: ${cssv(stack)};`);
      if (
        !noteEmitted &&
        opts.fontLoadingNote !== false &&
        (!googleFonts || googleFonts.length === 0)
      ) {
        lines.push(`  /* TODO: load these fonts via next/font or a <link> in your <head>. */`);
        noteEmitted = true;
      }
    }
  }

  // Placeholder typeset tokens so `text-h1` / `leading-body` / `tracking-h2`
  // exist as utilities; typeset.css supplies the real, rhythm-derived values.
  lines.push(...typesetThemeTokens());

  appendColorBlock(theme.colors, lines);
  appendPalette(theme.palette, lines);
  appendSpacing(theme.spacing, lines);
  appendShadows(theme.shadows, lines);
  appendAnimations(theme.animation, lines);
  // Keyframes live inside @theme so Tailwind v4 emits them on `animate-*` use.
  const keyframesCss = keyframesToCss(theme.keyframes, "  ");
  if (keyframesCss) lines.push(keyframesCss);

  lines.push(`}`);
  lines.push("");

  // Dark-mode overrides. shadcn convention: a `.dark` class on <html> or <body>
  // re-points the --color-* tokens. We emit one block keyed off `.dark` so users
  // can hook it up to any framework's dark-mode toggle (Tailwind v4 darkVariant
  // defaults to `prefers-color-scheme`; most apps swap to a class-based variant
  // via `@custom-variant dark (&:is(.dark *))` in their globals.css).
  if (theme.colorsDark || theme.paletteDark) {
    lines.push(`@custom-variant dark (&:is(.dark *));`);
    lines.push("");
    lines.push(`.dark {`);
    appendColorBlock(theme.colorsDark ?? {}, lines);
    appendPalette(theme.paletteDark, lines);
    lines.push(`}`);
    lines.push("");
  }

  lines.push(`@layer base {`);
  lines.push(`  * {`);
  lines.push(`    border-color: var(--color-border);`);
  lines.push(`  }`);
  lines.push(`  body {`);
  lines.push(`    background-color: var(--color-background);`);
  lines.push(`    color: var(--color-foreground);`);
  lines.push(`    font-family: var(--font-sans);`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");

  // Container override. Tailwind v4 dropped the `center`/`padding` config, so a
  // custom `@utility container` is the supported way to restore them.
  const container = theme.container;
  if (container && (container.center || container.padding || container.maxWidth)) {
    lines.push(`@utility container {`);
    lines.push(`  width: 100%;`);
    if (container.center) lines.push(`  margin-inline: auto;`);
    if (container.padding) lines.push(`  padding-inline: ${cssv(container.padding)};`);
    if (container.maxWidth) lines.push(`  max-width: ${cssv(container.maxWidth)};`);
    lines.push(`}`);
    lines.push("");
  }

  if (opts.customCss && opts.customCss.trim() !== "") {
    lines.push(`/* === velloo theme/custom.css === */`);
    // Emitted into the app's globals.css as-is, but neutralize the raw-text
    // breakout so a hostile custom.css can't smuggle markup when this string is
    // later inlined into a <style> (canvas parity + defense in the shipped app).
    lines.push(neutralizeCssText(opts.customCss.trimEnd()));
    lines.push("");
  }

  return lines.join("\n");
}
