/** Next.js-shaped defaults; Vite/Astro/Remix hosts pass their own. */
const DEFAULT_CONTENT_GLOBS = [
  "./app/**/*.{ts,tsx}",
  "./components/**/*.{ts,tsx}",
  "./pages/**/*.{ts,tsx}",
] as const;

/**
 * Emit a minimal Tailwind v4 config. Most of the tokens live in globals.css
 * via @theme; this file is the framework hook for `content` paths + plugins.
 */
export function emitTailwindConfig(
  contentGlobs: readonly string[] = DEFAULT_CONTENT_GLOBS,
): string {
  const content = contentGlobs.map((g) => `    ${JSON.stringify(g)},`).join("\n");
  return `import type { Config } from "tailwindcss";

/**
 * Generated by velloo. Tokens live in \`globals.css\` via Tailwind v4's
 * @theme directive; this file only registers content paths for scanning.
 */
export default {
  content: [
${content}
  ],
} satisfies Config;
`;
}
