/**
 * Emit a minimal Tailwind v4 config. Most of the tokens live in globals.css
 * via @theme; this file is the framework hook for `content` paths + plugins.
 */
export function emitTailwindConfig(): string {
  return `import type { Config } from "tailwindcss";

/**
 * Generated by velloo. Tokens live in \`globals.css\` via Tailwind v4's
 * @theme directive; this file only registers content paths for scanning.
 */
export default {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./pages/**/*.{ts,tsx}",
  ],
} satisfies Config;
`;
}
