import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import {
  type ColorPair,
  sanitizeCssTokenValue as cssv,
  isCssIdent,
  neutralizeCssText,
  sanitizeGoogleFontSpec,
  type Theme,
  typesetUtilityClasses,
  typesetV3FontSize,
} from "@velloo/schema";
import { diffFile } from "../diff.ts";
import { formatCss } from "../format.ts";
import { emitDtcgFile } from "./dtcg.ts";
import {
  COLOR_SLOTS,
  emitTypesetCss,
  paletteShadowedSlots,
  SEMANTIC_SLOTS,
} from "./globals-css.ts";
import { hslTriplet } from "./hsl.ts";
import type { EmitThemeFile, EmitThemeOptions, EmitThemeResult } from "./index.ts";

/**
 * Tailwind v3 theme emit — the stock-shadcn-v3 projection of the same Theme
 * the v4 path emits as `@theme` globals.css. Two velloo-owned artifacts:
 *
 * - `velloo-theme.css`: `:root` / `.dark` variables as raw HSL triplets inside
 *   `@layer base`, written NEXT TO the app's globals.css (never into it — a v3
 *   app's `@tailwind` directives are its own).
 * - `velloo.preset.{ts,cjs}`: a Tailwind preset mapping the variables under
 *   `theme.extend` with `<alpha-value>` plumbing, plus radius / fonts /
 *   spacing / shadows / keyframes / container. The user's config keeps its
 *   content globs and plugins and adds one `presets: [...]` line.
 *
 * Round-trip symmetry: `parseThemeCss` reads exactly this vocabulary back
 * (the v3-era branch it has always supported).
 */

interface ThemeVar {
  name: string;
  light?: string;
  dark?: string;
  /** Every declared value converted to an HSL triplet (enables `<alpha-value>`). */
  triplet: boolean;
}

function defaultOf(value: ColorPair | undefined): string | undefined {
  if (typeof value === "string") return value;
  return value?.DEFAULT;
}

function fgOf(value: ColorPair | undefined): string | undefined {
  if (value && typeof value === "object") return value.foreground;
  return undefined;
}

/** Build one var, converting to triplets when every declared value converts. */
function themeVar(name: string, light: string | undefined, dark: string | undefined): ThemeVar {
  const lightT = light !== undefined ? hslTriplet(light) : null;
  const darkT = dark !== undefined ? hslTriplet(dark) : null;
  const triplet =
    (light === undefined || lightT !== null) && (dark === undefined || darkT !== null);
  return {
    name,
    ...(light !== undefined ? { light: triplet ? (lightT as string) : light } : {}),
    ...(dark !== undefined ? { dark: triplet ? (darkT as string) : dark } : {}),
    triplet,
  };
}

/** Semantic color slots + palette entries as CSS vars, in emit order. */
function collectVars(theme: Theme, warnings: string[]): ThemeVar[] {
  const vars: ThemeVar[] = [];
  for (const { key, pair } of COLOR_SLOTS) {
    const light = defaultOf(theme.colors[key]);
    const dark = defaultOf(theme.colorsDark?.[key]);
    if (light !== undefined || dark !== undefined) vars.push(themeVar(key, light, dark));
    if (pair) {
      const lightFg = fgOf(theme.colors[key]);
      const darkFg = fgOf(theme.colorsDark?.[key]);
      if (lightFg !== undefined || darkFg !== undefined) {
        vars.push(themeVar(`${key}-foreground`, lightFg, darkFg));
      }
    }
  }
  const paletteNames = new Set([
    ...Object.keys(theme.palette ?? {}),
    ...Object.keys(theme.paletteDark ?? {}),
  ]);
  for (const name of [...paletteNames].sort()) {
    if (!isCssIdent(name) || SEMANTIC_SLOTS.has(name)) continue;
    vars.push(themeVar(name, theme.palette?.[name], theme.paletteDark?.[name]));
  }
  for (const v of vars) {
    if (!v.triplet) {
      warnings.push(
        `--${v.name} could not be expressed as an HSL triplet — mapped as a raw var() in the preset, so opacity modifiers (\`bg-${v.name}/50\`) won't work for it.`,
      );
    }
  }
  return vars;
}

/** How a var is painted in plain CSS (the base-layer body/border rules). */
function paint(v: ThemeVar): string {
  return v.triplet ? `hsl(var(--${v.name}))` : `var(--${v.name})`;
}

/** How a var is referenced from the preset's `theme.extend.colors`. */
function configColor(v: ThemeVar): string {
  return v.triplet ? `hsl(var(--${v.name}) / <alpha-value>)` : `var(--${v.name})`;
}

/** The typeset sheet's filename on the v3 path — velloo-prefixed like its sibling. */
const TYPESET_CSS_V3_FILENAME = "velloo-typeset.css";

/** The `--radius` base, mirroring the v4 emitter's precedence. */
function radiusBase(theme: Theme): string | undefined {
  const raw = theme.radius.md ?? theme.radius.lg ?? theme.radius.sm;
  if (raw === undefined) return undefined;
  return typeof raw === "number" ? `${raw}px` : cssv(raw);
}

export function emitGlobalsCssV3(
  theme: Theme,
  vars: ThemeVar[],
  opts: { customCss?: string | undefined } = {},
): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * Generated by velloo from theme "${cssv(theme.name)}" — Tailwind v3 variables.`);
  lines.push(` * Import from the top of your globals.css: @import "./velloo-theme.css";`);
  lines.push(` * Hand-edits are welcome; re-running \`velloo theme:export\` shows a diff.`);
  lines.push(` */`);
  const googleFonts = theme.typography.googleFonts;
  if (googleFonts && googleFonts.length > 0) {
    const families = googleFonts.map((f) => `family=${sanitizeGoogleFontSpec(f)}`).join("&");
    lines.push(`@import url("https://fonts.googleapis.com/css2?${families}&display=swap");`);
  }
  lines.push("");
  lines.push(`@layer base {`);
  lines.push(`  :root {`);
  const radius = radiusBase(theme);
  if (radius !== undefined) lines.push(`    --radius: ${radius};`);
  for (const v of vars) {
    if (v.light !== undefined) lines.push(`    --${v.name}: ${cssv(v.light)};`);
  }
  lines.push(`  }`);
  if (vars.some((v) => v.dark !== undefined)) {
    lines.push("");
    lines.push(`  .dark {`);
    for (const v of vars) {
      if (v.dark !== undefined) lines.push(`    --${v.name}: ${cssv(v.dark)};`);
    }
    lines.push(`  }`);
  }
  const border = vars.find((v) => v.name === "border");
  const background = vars.find((v) => v.name === "background");
  const foreground = vars.find((v) => v.name === "foreground");
  lines.push("");
  if (border) {
    lines.push(`  * {`);
    lines.push(`    border-color: ${paint(border)};`);
    lines.push(`  }`);
  }
  if (background || foreground) {
    lines.push(`  body {`);
    if (background) lines.push(`    background-color: ${paint(background)};`);
    if (foreground) lines.push(`    color: ${paint(foreground)};`);
    lines.push(`  }`);
  }
  lines.push(`}`);
  lines.push("");

  if (opts.customCss && opts.customCss.trim() !== "") {
    lines.push(`/* === velloo theme/custom.css === */`);
    lines.push(neutralizeCssText(opts.customCss.trimEnd()));
    lines.push("");
  }

  return lines.join("\n");
}

/** The preset's data shape — serialized with JSON.stringify, so plain values only. */
function presetObject(theme: Theme, vars: ThemeVar[]): Record<string, unknown> {
  const colors: Record<string, unknown> = {};
  const byName = new Map(vars.map((v) => [v.name, v]));
  for (const { key, pair } of COLOR_SLOTS) {
    const base = byName.get(key);
    if (!base) continue;
    const fg = pair ? byName.get(`${key}-foreground`) : undefined;
    colors[key] = fg
      ? { DEFAULT: configColor(base), foreground: configColor(fg) }
      : configColor(base);
  }
  for (const v of vars) {
    if (!SEMANTIC_SLOTS.has(v.name) && !(v.name in colors)) colors[v.name] = configColor(v);
  }

  const extend: Record<string, unknown> = { colors };

  if (radiusBase(theme) !== undefined) {
    // The stock shadcn-v3 ladder off the single --radius base.
    extend.borderRadius = {
      lg: "var(--radius)",
      md: "calc(var(--radius) - 2px)",
      sm: "calc(var(--radius) - 4px)",
    };
  }

  const fonts = theme.typography.fontFamily;
  if (fonts) {
    const fontFamily: Record<string, string> = {};
    for (const [role, stack] of Object.entries(fonts)) {
      if (isCssIdent(role)) fontFamily[role] = stack;
    }
    if (Object.keys(fontFamily).length > 0) extend.fontFamily = fontFamily;
  }

  // The typeset ladder. Values are `var()` references into velloo-typeset.css,
  // so `text-h1` re-derives inside a `.typeset-<preset>` region just as it does
  // under v4's @theme.
  extend.fontSize = typesetV3FontSize();

  const spacing: Record<string, string> = {};
  for (const [name, value] of Object.entries(theme.spacing)) {
    if (!Number.isNaN(Number(name))) continue;
    if (!isCssIdent(name)) continue;
    if (typeof value === "string" || typeof value === "number") spacing[name] = String(value);
  }
  if (Object.keys(spacing).length > 0) extend.spacing = spacing;

  const boxShadow: Record<string, string> = {};
  for (const [name, value] of Object.entries(theme.shadows ?? {})) {
    if (!isCssIdent(name)) continue;
    if (typeof value === "string" || typeof value === "number") boxShadow[name] = String(value);
  }
  if (Object.keys(boxShadow).length > 0) extend.boxShadow = boxShadow;

  if (theme.keyframes) {
    const keyframes: Record<string, unknown> = {};
    for (const [name, steps] of Object.entries(theme.keyframes)) {
      if (isCssIdent(name)) keyframes[name] = steps;
    }
    if (Object.keys(keyframes).length > 0) extend.keyframes = keyframes;
  }
  if (theme.animation && Object.keys(theme.animation).length > 0) {
    extend.animation = theme.animation;
  }

  // v3 has no `@source inline(...)`: the typeset ladder's class literals live in
  // @velloo/schema and appear in no scanned file, so safelist them or the
  // Heading/Text defaults never compile.
  const preset: Record<string, unknown> = {
    darkMode: ["class"],
    safelist: typesetUtilityClasses(),
  };
  const themeSection: Record<string, unknown> = {};
  const container = theme.container;
  if (container && (container.center || container.padding || container.maxWidth)) {
    themeSection.container = {
      ...(container.center ? { center: true } : {}),
      ...(container.padding ? { padding: container.padding } : {}),
      ...(container.maxWidth ? { screens: { "2xl": container.maxWidth } } : {}),
    };
  }
  themeSection.extend = extend;
  preset.theme = themeSection;
  return preset;
}

export function emitTailwindPresetV3(
  theme: Theme,
  vars: ThemeVar[],
  moduleKind: "ts" | "cjs",
): string {
  const body = JSON.stringify(presetObject(theme, vars), null, 2);
  const wiring =
    moduleKind === "ts"
      ? `import vellooPreset from "./velloo.preset";\n *   ...\n *   presets: [vellooPreset],`
      : `presets: [require("./velloo.preset.cjs")],`;
  const header = `/**
 * Generated by velloo from theme "${cssv(theme.name)}" — Tailwind v3 preset.
 *
 * Wire it into your tailwind config once:
 *   ${wiring}
 * Your content globs and plugins stay in your own config; velloo only ever
 * rewrites this file. Pair it with velloo-theme.css (the CSS variables).
 */
`;
  return moduleKind === "ts"
    ? `${header}export default ${body};\n`
    : `${header}module.exports = ${body};\n`;
}

/** Whether the target app's own config is TypeScript — picks the preset flavor. */
function presetModuleKind(outputDir: string): "ts" | "cjs" {
  for (const name of ["tailwind.config.ts", "tailwind.config.mts", "tailwind.config.cts"]) {
    if (existsSync(join(outputDir, name))) return "ts";
  }
  return "cjs";
}

/**
 * The theme-css location: `velloo-theme.css` in the same directory as the
 * caller-supplied globals path. Never the globals file itself — overwriting a
 * v3 app's globals.css would clobber its `@tailwind` directives.
 */
function v3CssRelPath(cssPath: string | undefined): string {
  const requested = cssPath ?? "app/globals.css";
  if (basename(requested) === "velloo-theme.css") return requested;
  const dir = dirname(requested);
  return dir === "." ? "velloo-theme.css" : join(dir, "velloo-theme.css");
}

export async function emitThemeV3(
  theme: Theme,
  options: EmitThemeOptions,
): Promise<EmitThemeResult> {
  const files: EmitThemeFile[] = [];
  const warnings: string[] = [];
  const shadowed = paletteShadowedSlots(theme);
  if (shadowed.length > 0) {
    warnings.push(
      `Skipped palette token${shadowed.length > 1 ? "s" : ""} ${shadowed.map((n) => `\`${n}\``).join(", ")}: ` +
        `each would shadow the semantic \`--${shadowed[0]}\`-style slot. Set the semantic slot itself or rename the palette token.`,
    );
  }
  const vars = collectVars(theme, warnings);

  const cssRel = v3CssRelPath(options.cssPath);
  const cssPath = join(options.outputDir, cssRel);
  const cssRaw = emitGlobalsCssV3(theme, vars, {
    ...(options.customCss !== undefined ? { customCss: options.customCss } : {}),
  });
  const cssFormatted = await formatCss(cssPath, cssRaw);
  const cssDiff = await diffFile(cssPath, cssFormatted.output);
  let cssApplied = false;
  if (options.apply && !cssDiff.identical) {
    await mkdir(dirname(cssPath), { recursive: true });
    await writeFile(cssPath, cssFormatted.output, "utf8");
    cssApplied = true;
  }
  files.push({
    path: cssPath,
    contents: cssFormatted.output,
    diff: cssDiff,
    applied: cssApplied,
    errors: cssFormatted.errors,
  });

  // The typeset sheet, alongside velloo-theme.css. Same generator as v4 and as
  // the canvas — only the wiring differs (a preset instead of `@theme`).
  const typesetRel = join(dirname(cssRel), TYPESET_CSS_V3_FILENAME);
  const typesetPath = join(options.outputDir, typesetRel);
  const typesetRaw = emitTypesetCss(theme);
  const typesetFormatted = await formatCss(typesetPath, typesetRaw);
  const typesetDiff = await diffFile(typesetPath, typesetFormatted.output);
  let typesetApplied = false;
  if (options.apply && !typesetDiff.identical) {
    await mkdir(dirname(typesetPath), { recursive: true });
    await writeFile(typesetPath, typesetFormatted.output, "utf8");
    typesetApplied = true;
  }
  files.push({
    path: typesetPath,
    contents: typesetFormatted.output,
    diff: typesetDiff,
    applied: typesetApplied,
    errors: typesetFormatted.errors,
  });

  const moduleKind = presetModuleKind(options.outputDir);
  const presetName = moduleKind === "ts" ? "velloo.preset.ts" : "velloo.preset.cjs";
  if (!options.cssOnly) {
    const presetPath = join(options.outputDir, presetName);
    const presetRaw = emitTailwindPresetV3(theme, vars, moduleKind);
    const presetDiff = await diffFile(presetPath, presetRaw);
    let presetApplied = false;
    if (options.apply && !presetDiff.identical) {
      await mkdir(dirname(presetPath), { recursive: true });
      await writeFile(presetPath, presetRaw, "utf8");
      presetApplied = true;
    }
    files.push({
      path: presetPath,
      contents: presetRaw,
      diff: presetDiff,
      applied: presetApplied,
      errors: [],
    });
  }

  const dtcg = await emitDtcgFile(theme, options);
  files.push(dtcg.file);
  warnings.push(...dtcg.warnings);

  const notes = [
    `Tailwind v3 target: emitted ${cssRel} + ${typesetRel}${options.cssOnly ? "" : ` + ${presetName}`} instead of a v4 globals.css.`,
    `Add \`@import "./velloo-theme.css";\` and \`@import "./${TYPESET_CSS_V3_FILENAME}";\` at the very top of your globals stylesheet (before the @tailwind directives — postcss-import requires @import rules first).`,
    ...(options.cssOnly
      ? []
      : [
          moduleKind === "ts"
            ? `Register the preset in tailwind.config.ts: \`import vellooPreset from "./velloo.preset"\` then \`presets: [vellooPreset]\`.`
            : `Register the preset in your tailwind config: \`presets: [require("./velloo.preset.cjs")]\`.`,
        ]),
  ];

  return { files, warnings, notes };
}
