import {
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Avatar,
  Badge,
  Box,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Checkbox,
  Container,
  chakra,
  Divider,
  Flex,
  Grid,
  GridItem,
  Heading,
  HStack,
  IconButton,
  Input,
  List,
  ListItem,
  Progress,
  Radio,
  Select,
  Skeleton,
  Slider,
  SliderFilledTrack,
  SliderThumb,
  SliderTrack,
  Spacer,
  Stack,
  Stat,
  StatArrow,
  StatHelpText,
  StatLabel,
  StatNumber,
  Switch,
  Tab,
  TabList,
  Table,
  TableContainer,
  TabPanel,
  TabPanels,
  Tabs,
  Tag,
  Tbody,
  Td,
  Text,
  Textarea,
  Th,
  Thead,
  Tr,
  VStack,
} from "@chakra-ui/react";
import {
  Gradient as VellooGradient,
  Icon as VellooIcon,
  Image as VellooImage,
  Layer as VellooLayer,
  Placeholder as VellooPlaceholder,
  Prose as VellooProse,
  SVG as VellooSVG,
} from "@velloo/helpers";
import type { ComponentRegistry } from "@velloo/provider";
import {
  Drawer,
  DrawerBody,
  DrawerContent,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  Menu,
  MenuButton,
  MenuDivider,
  MenuItem,
  MenuList,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Popover,
  PopoverArrow,
  PopoverBody,
  PopoverContent,
  PopoverHeader,
  PopoverTrigger,
  Tooltip,
} from "./overlays.ts";

// `chakra()` makes sx resolve through the same theme/runtime as native Chakra
// primitives while preserving each helper's Velloo-specific behavior.
const helperRegistry: ComponentRegistry = {
  Icon: chakra(VellooIcon),
  Image: chakra(VellooImage, {
    // Velloo's fill-mode Image owns a wrapper. Keep layout styles (including
    // width/height) on that root, and let ordinary Chakra `objectFit` /
    // `objectPosition` values flow through to the actual child image.
    baseStyle: {
      objectFit: "cover",
      objectPosition: "50% 50%",
      "& > img": { objectFit: "inherit", objectPosition: "inherit" },
    },
  }),
  Placeholder: chakra(VellooPlaceholder),
  SVG: chakra(VellooSVG),
  Layer: chakra(VellooLayer),
  Gradient: chakra(VellooGradient),
  Prose: chakra(VellooProse),
};

/**
 * The runtime registry for chakra-native folders: design `$ref` ids → real
 * Chakra v2 components, SSR'd in-process via the adapter's emotion render
 * pass. The overlay surface (Modal/Drawer/Popover/Menu/Tooltip and their
 * composition parts) is canvas-safe-wrapped in `overlays.ts` — chakra's own
 * overlays portal and render NOTHING in SSR, and their sub-parts throw
 * outside the real parent's context, so the shims render the whole
 * composition open + inline. Chakra's own `Icon`/`Image` are deliberately not
 * registered — those ids belong to the framework-neutral velloo helpers
 * (Icon → lucide), like on the MUI/antd folders.
 */
export const registry: ComponentRegistry = {
  // layout
  Box,
  Container,
  Flex,
  Grid,
  GridItem,
  HStack,
  Spacer,
  Stack,
  VStack,
  // surfaces + data display
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Avatar,
  Badge,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Divider,
  Progress,
  Skeleton,
  Stat,
  StatArrow,
  StatHelpText,
  StatLabel,
  StatNumber,
  Tag,
  // typography
  Heading,
  Text,
  // controls
  Button,
  Checkbox,
  IconButton,
  Input,
  Radio,
  Select,
  Slider,
  SliderFilledTrack,
  SliderThumb,
  SliderTrack,
  Switch,
  Textarea,
  // data
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  List,
  ListItem,
  Tab,
  Table,
  TableContainer,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  // overlays (canvas-safe shims)
  Drawer,
  DrawerBody,
  DrawerContent,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  Menu,
  MenuButton,
  MenuDivider,
  MenuItem,
  MenuList,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Popover,
  PopoverArrow,
  PopoverBody,
  PopoverContent,
  PopoverHeader,
  PopoverTrigger,
  Tooltip,
  // Framework-neutral behavior, wrapped so Chakra's sx channel styles the
  // helper root just like it styles Box/Button/Card.
  ...helperRegistry,
};
