import {
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Avatar,
  Badge,
  Box,
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Checkbox,
  Container,
  Divider,
  Flex,
  Grid,
  GridItem,
  Heading,
  HStack,
  IconButton,
  Input,
  List,
  ListItem,
  Progress,
  Radio,
  Select,
  Skeleton,
  Slider,
  SliderFilledTrack,
  SliderThumb,
  SliderTrack,
  Spacer,
  Stack,
  Stat,
  StatArrow,
  StatHelpText,
  StatLabel,
  StatNumber,
  Switch,
  Tab,
  TabList,
  Table,
  TableContainer,
  TabPanel,
  TabPanels,
  Tabs,
  Tag,
  Tbody,
  Td,
  Text,
  Textarea,
  Th,
  Thead,
  Tr,
  VStack,
} from "@chakra-ui/react";
import { helpersRegistry } from "@velloo/helpers";
import type { ComponentRegistry } from "@velloo/provider";
import {
  Drawer,
  DrawerBody,
  DrawerContent,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  Menu,
  MenuButton,
  MenuDivider,
  MenuItem,
  MenuList,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Popover,
  PopoverArrow,
  PopoverBody,
  PopoverContent,
  PopoverHeader,
  PopoverTrigger,
  Tooltip,
} from "./overlays.ts";

const REUSED_HELPER_IDS = ["Icon", "Image", "Placeholder", "SVG", "Layer", "Gradient"] as const;

/**
 * The runtime registry for chakra-native folders: design `$ref` ids → real
 * Chakra v2 components, SSR'd in-process via the adapter's emotion render
 * pass. The overlay surface (Modal/Drawer/Popover/Menu/Tooltip and their
 * composition parts) is canvas-safe-wrapped in `overlays.ts` — chakra's own
 * overlays portal and render NOTHING in SSR, and their sub-parts throw
 * outside the real parent's context, so the shims render the whole
 * composition open + inline. Chakra's own `Icon`/`Image` are deliberately not
 * registered — those ids belong to the framework-neutral velloo helpers
 * (Icon → lucide), like on the MUI/antd folders.
 */
export const registry: ComponentRegistry = {
  // layout
  Box,
  Container,
  Flex,
  Grid,
  GridItem,
  HStack,
  Spacer,
  Stack,
  VStack,
  // surfaces + data display
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Avatar,
  Badge,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  Divider,
  Progress,
  Skeleton,
  Stat,
  StatArrow,
  StatHelpText,
  StatLabel,
  StatNumber,
  Tag,
  // typography
  Heading,
  Text,
  // controls
  Button,
  Checkbox,
  IconButton,
  Input,
  Radio,
  Select,
  Slider,
  SliderFilledTrack,
  SliderThumb,
  SliderTrack,
  Switch,
  Textarea,
  // data
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  List,
  ListItem,
  Tab,
  Table,
  TableContainer,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  // overlays (canvas-safe shims)
  Drawer,
  DrawerBody,
  DrawerContent,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  Menu,
  MenuButton,
  MenuDivider,
  MenuItem,
  MenuList,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Popover,
  PopoverArrow,
  PopoverBody,
  PopoverContent,
  PopoverHeader,
  PopoverTrigger,
  Tooltip,
  // Framework-neutral velloo helpers chakra has no equivalent for — chiefly
  // `Icon` (lucide; @chakra-ui/icons isn't surfaced) + imagery/composition
  // helpers. Reused verbatim from `@velloo/helpers`, like provider-mui. They
  // size via props (`Icon size`), not Tailwind — the JIT is off on a chakra folder.
  ...helpersRegistry(REUSED_HELPER_IDS),
};
