import type { CommandSpec } from "./spec.ts";

export type Shell = "zsh" | "bash" | "fish";

export const SHELLS: Shell[] = ["zsh", "bash", "fish"];

/** zsh `_describe` entries delimit on `:` — escape it in names (theme:export). */
const zshName = (name: string) => name.replace(/:/g, "\\:");

function zshScript(specs: CommandSpec[]): string {
  const commandLines = specs.map((c) => `    '${zshName(c.name)}:${c.description}'`).join("\n");
  const cases = specs
    .map((c) => {
      const flagSpecs = c.flags
        .map((f) => `        '${f.flag}${f.takesValue ? "=" : ""}[${f.description}]'`)
        .join(" \\\n");
      const body = flagSpecs
        ? `      _arguments \\\n${flagSpecs} \\\n        '*:file:_files'`
        : `      _files`;
      return `    ${c.name})\n${body}\n      ;;`;
    })
    .join("\n");
  return `#compdef velloo
# velloo shell completions (zsh) — generated by \`velloo completions\`.
_velloo() {
  local -a _velloo_commands
  _velloo_commands=(
${commandLines}
  )
  if (( CURRENT == 2 )); then
    _describe 'velloo command' _velloo_commands
    return
  fi
  case $words[2] in
${cases}
  esac
}
if ! (( $+functions[compdef] )); then
  autoload -Uz compinit && compinit -i
fi
compdef _velloo velloo
`;
}

function bashScript(specs: CommandSpec[]): string {
  const names = specs.map((c) => c.name).join(" ");
  const cases = specs
    .map((c) => `    ${c.name}) flags="${c.flags.map((f) => f.flag).join(" ")}" ;;`)
    .join("\n");
  return `# velloo shell completions (bash) — generated by \`velloo completions\`.
_velloo() {
  local cur cmd flags
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cmd="\${COMP_WORDS[1]}"
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${names}" -- "$cur") )
    return
  fi
  flags=""
  case "$cmd" in
${cases}
  esac
  if [[ "$cur" == -* && -n "$flags" ]]; then
    COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
  fi
}
complete -o default -F _velloo velloo
`;
}

function fishScript(specs: CommandSpec[]): string {
  const lines: string[] = [
    "# velloo shell completions (fish) — generated by `velloo completions`.",
  ];
  for (const c of specs) {
    lines.push(
      `complete -c velloo -f -n "__fish_use_subcommand" -a "${c.name}" -d "${c.description}"`,
    );
    for (const f of c.flags) {
      const long = f.flag.replace(/^--/, "");
      lines.push(
        `complete -c velloo -n "__fish_seen_subcommand_from ${c.name}" -l ${long}${f.takesValue ? " -r" : ""} -d "${f.description}"`,
      );
    }
  }
  return `${lines.join("\n")}\n`;
}

/** Render the completion script for one shell from the introspected spec. */
export function completionScript(shell: Shell, specs: CommandSpec[]): string {
  switch (shell) {
    case "zsh":
      return zshScript(specs);
    case "bash":
      return bashScript(specs);
    case "fish":
      return fishScript(specs);
  }
}
