import type { CommandSpec } from "./spec.ts";

export type Shell = "zsh" | "bash" | "fish";

export const SHELLS: Shell[] = ["zsh", "bash", "fish"];

/** zsh `_describe` entries delimit on `:` — escape it in names. */
const zshName = (name: string) => name.replace(/\\/g, "\\\\").replace(/:/g, "\\:");

/** `_arguments` for one command's flags, falling back to files for positionals. */
function zshArguments(c: CommandSpec, indent: string): string {
  const flagSpecs = c.flags
    .map((f) => `${indent}  '${f.flag}${f.takesValue ? "=" : ""}[${f.description}]'`)
    .join(" \\\n");
  return flagSpecs
    ? `${indent}_arguments \\\n${flagSpecs} \\\n${indent}  '*:file:_files'`
    : `${indent}_files`;
}

function zshScript(specs: CommandSpec[]): string {
  const commandLines = specs.map((c) => `    '${zshName(c.name)}:${c.description}'`).join("\n");
  const cases = specs
    .map((c) => {
      if (c.subcommands.length === 0)
        return `    ${c.name})\n${zshArguments(c, "      ")}\n      ;;`;
      const subLines = c.subcommands
        .map((sub) => `          '${zshName(sub.name)}:${sub.description}'`)
        .join("\n");
      const subCases = c.subcommands
        .map((sub) => `        ${sub.name})\n${zshArguments(sub, "          ")}\n          ;;`)
        .join("\n");
      const own = c.flags.length > 0 ? `\n${zshArguments(c, "        ")}` : "";
      const fallback =
        c.flags.length > 0 ? `\n        *)\n${zshArguments(c, "          ")}\n          ;;` : "";
      return `    ${c.name})
      if (( CURRENT == 3 )); then
        local -a _velloo_subcommands
        _velloo_subcommands=(
${subLines}
        )
        _describe 'velloo ${c.name} command' _velloo_subcommands${own}
        return
      fi
      case $words[3] in
${subCases}${fallback}
      esac
      ;;`;
    })
    .join("\n");
  return `#compdef velloo
# velloo shell completions (zsh) — generated by \`velloo completions\`.
_velloo() {
  local -a _velloo_commands
  _velloo_commands=(
${commandLines}
  )
  if (( CURRENT == 2 )); then
    _describe 'velloo command' _velloo_commands
    return
  fi
  case $words[2] in
${cases}
  esac
}
if ! (( $+functions[compdef] )); then
  autoload -Uz compinit && compinit -i
fi
compdef _velloo velloo
`;
}

const flagWords = (c: CommandSpec) => c.flags.map((f) => f.flag).join(" ");

function bashScript(specs: CommandSpec[]): string {
  const names = specs.map((c) => c.name).join(" ");
  const cases = specs
    .map((c) => {
      if (c.subcommands.length === 0) return `    ${c.name}) flags="${flagWords(c)}" ;;`;
      const subCases = c.subcommands
        .map((sub) => `        ${sub.name}) flags="${flagWords(sub)}" ;;`)
        .join("\n");
      return `    ${c.name})
      subs="${c.subcommands.map((sub) => sub.name).join(" ")}"
      case "$sub" in
${subCases}
        *) flags="${flagWords(c)}" ;;
      esac
      ;;`;
    })
    .join("\n");
  return `# velloo shell completions (bash) — generated by \`velloo completions\`.
_velloo() {
  local cur cmd sub subs flags
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cmd="\${COMP_WORDS[1]}"
  sub="\${COMP_WORDS[2]}"
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${names}" -- "$cur") )
    return
  fi
  subs=""
  flags=""
  case "$cmd" in
${cases}
  esac
  if [[ $COMP_CWORD -eq 2 && -n "$subs" && "$cur" != -* ]]; then
    COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    return
  fi
  if [[ "$cur" == -* && -n "$flags" ]]; then
    COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
  fi
}
complete -o default -F _velloo velloo
`;
}

function fishFlags(c: CommandSpec, condition: string): string[] {
  return c.flags.map((f) => {
    const long = f.flag.replace(/^--/, "");
    return `complete -c velloo -n "${condition}" -l ${long}${f.takesValue ? " -r" : ""} -d "${f.description}"`;
  });
}

function fishScript(specs: CommandSpec[]): string {
  const lines: string[] = [
    "# velloo shell completions (fish) — generated by `velloo completions`.",
    // Matching on the leading words, not `__fish_seen_subcommand_from`, keeps
    // `velloo theme export` from picking up the flags of `velloo export`.
    "function __velloo_is",
    "  set -l words",
    "  for token in (commandline -opc)[2..-1]",
    "    string match -q -- '-*' $token; or set -a words $token",
    "  end",
    '  test "$words[1]" = "$argv[1]"; or return 1',
    "  test (count $argv) -lt 2; and return 0",
    '  test "$words[2]" = "$argv[2]"',
    "end",
    "function __velloo_words",
    "  set -l words",
    "  for token in (commandline -opc)[2..-1]",
    "    string match -q -- '-*' $token; or set -a words $token",
    "  end",
    "  count $words",
    "end",
  ];
  for (const c of specs) {
    lines.push(
      `complete -c velloo -f -n "__fish_use_subcommand" -a "${c.name}" -d "${c.description}"`,
    );
    if (c.subcommands.length === 0) {
      lines.push(...fishFlags(c, `__velloo_is ${c.name}`));
      continue;
    }
    for (const sub of c.subcommands) {
      lines.push(
        `complete -c velloo -f -n "__velloo_is ${c.name}; and test (__velloo_words) -eq 1" -a "${sub.name}" -d "${sub.description}"`,
      );
      lines.push(...fishFlags(sub, `__velloo_is ${c.name} ${sub.name}`));
    }
    const notSub = c.subcommands
      .map((sub) => `; and not __velloo_is ${c.name} ${sub.name}`)
      .join("");
    lines.push(...fishFlags(c, `__velloo_is ${c.name}${notSub}`));
  }
  return `${lines.join("\n")}\n`;
}

/** Render the completion script for one shell from the introspected spec. */
export function completionScript(shell: Shell, specs: CommandSpec[]): string {
  switch (shell) {
    case "zsh":
      return zshScript(specs);
    case "bash":
      return bashScript(specs);
    case "fish":
      return fishScript(specs);
  }
}
