import { existsSync } from "node:fs";
import { join } from "node:path";
import {
  type CatalogEntry,
  type FrameworkAdapter,
  type InstallCtx,
  type Manifest,
  TAILWIND_CLASSNAME,
} from "@velloo/provider";
import {
  componentsDir as snapshotComponentsDir,
  entryCssPath as snapshotEntryCssPath,
  registry as snapshotRegistry,
  snapshotVersion,
} from "@velloo/shadcn-snapshot";
import { installedAddNames, runShadcnAdd, shadcnAddName } from "./install.ts";
import { readManifest } from "./manifest.ts";

/**
 * Build the `shadcn-upstream` ComponentProvider.
 *
 * The current shape — a pragmatic hybrid:
 *
 *  - **User-visible win**: components in the user's app are vanilla
 *    shadcn fetched at a pinned version (deposited by the fetcher
 *    into the chosen `componentsPath` directory).
 *  - **Canvas runtime**: still uses the `@velloo/shadcn-snapshot`
 *    registry. The snapshot's canvas-safe overlays already implement
 *    the adapter contract; the rest of the snapshot's components are
 *    near-byte-identical to upstream. Reusing the snapshot registry
 *    avoids bundling 25+ `@radix-ui/*` sub-packages into the velloo
 *    binary — a real cost the bundler-based architecture would carry.
 *  - **Tailwind JIT**: scans the fetched directory so user
 *    customizations to the on-disk files contribute to compiled CSS.
 *  - **Manifest**: prefers the per-cache `manifest.json` (generated by
 *    the fetcher against the fetched .tsx) so the inspector surfaces
 *    upstream prop schemas. Falls back to the snapshot's manifest when
 *    the cache is missing (e.g. during in-memory tests).
 *
 * The bundler-based canvas-from-upstream story is deferred for now.
 */
export interface CreateUpstreamProviderOptions {
  /**
   * Cache directory where fetched components live, e.g.
   * `~/.velloo/providers/shadcn-upstream@2026.05.26/` or a
   * user-app path like `../apps/web/src/components/`. The provider
   * uses this for componentsDir and the manifest source.
   */
  cacheDir?: string;
  /** Version string for the provider's `version` field — defaults to the snapshot's date. */
  version?: string;
  /**
   * Absolute path to the user's app — where `install_component` runs the
   * shadcn CLI and where installed-status is read from. Absent ⇒ the catalog
   * reports nothing installed and installs error with guidance.
   */
  hostAppRoot?: string;
}

export function createProvider(opts: CreateUpstreamProviderOptions = {}): FrameworkAdapter {
  const cacheDir = opts.cacheDir;
  const componentsDir =
    cacheDir && existsSync(join(cacheDir, "ui")) ? join(cacheDir, "ui") : snapshotComponentsDir;
  const version = opts.version ?? snapshotVersion;
  const hostAppRoot = opts.hostAppRoot;
  const loadManifest = async (): Promise<Manifest> => {
    if (cacheDir && existsSync(join(cacheDir, "manifest.json"))) {
      return await readManifest(cacheDir);
    }
    // Fall back to the snapshot's manifest if no cache was generated
    // (in-process tests, dev shortcuts).
    const { loadManifest: snapshotManifest } = await import("@velloo/shadcn-snapshot");
    return snapshotManifest();
  };
  return {
    id: "shadcn-upstream",
    version,
    componentsDir,
    styleEntryPath: snapshotEntryCssPath,
    registry: snapshotRegistry,
    loadManifest,
    label: `shadcn (upstream @ ${version})`,
    styleChannel: TAILWIND_CLASSNAME,
    styleChannels: ["tailwind-classname"],
    // The base instructions are already shadcn-shaped; the one thing worth
    // framing is that components land in the USER'S APP on demand.
    mcpIntro: () => [
      '**This folder targets shadcn/ui with Tailwind.** Components come from a pinned shadcn snapshot plus the velloo helpers (`Box` for layout, `Heading`/`Text`, `Icon`, `Image`, `Gradient`, `Layer`, `SVG`, `Divider`, `Placeholder`, `Prose`). Style through `update_props { style: "flex gap-4 p-6" }` — a Tailwind className string. Call `list_components` for the full set and per-component `example` props.',
      "",
      "**Installing components into the app**: this folder's shadcn components render on the canvas from velloo's built-in runtime, but the user's app only contains what has been installed. When the design uses a component the app doesn't have yet (or you're about to emit code that imports one), call `install_component { componentId }` — it runs the official `npx shadcn@latest add` in the host app and reports the import path. `install_component` also answers installed-status for any component id.",
      "",
    ],
    // Real installed-status per catalog() call: a component's shadcn family
    // file exists in the app's ui dir. The canvas renders everything from the
    // snapshot runtime either way — "installed" is about the USER'S APP.
    catalog: async (): Promise<CatalogEntry[]> => {
      const manifest = await loadManifest();
      const shadcn = manifest.filter((c) => c.source !== "velloo");
      const present = hostAppRoot ? installedAddNames(hostAppRoot) : new Set<string>();
      return shadcn.map((c) => {
        const addName = shadcnAddName(c.id);
        return {
          id: c.id,
          installed: present.has(addName),
          importPath: `@/components/ui/${addName}`,
        };
      });
    },
    installComponent: async (id: string, ctx: InstallCtx): Promise<void> => {
      const manifest = await loadManifest();
      const known = manifest.some((c) => c.source !== "velloo" && c.id === id);
      if (!known) {
        throw new Error(`"${id}" is not a shadcn component in this library's catalog.`);
      }
      const appRoot = ctx.hostAppRoot ?? hostAppRoot;
      if (!appRoot || !existsSync(appRoot)) {
        throw new Error(
          "No host app to install into — set `hostApp.root` in .design/config.json " +
            "(or re-run `velloo init` inside your app) so shadcn components can be added to it.",
        );
      }
      await runShadcnAdd({ hostAppRoot: appRoot, addName: shadcnAddName(id) });
    },
  };
}
