import { existsSync } from "node:fs";
import { join } from "node:path";
import type { ComponentProvider, Manifest } from "@velloo/provider";
import {
  componentsDir as snapshotComponentsDir,
  entryCssPath as snapshotEntryCssPath,
  registry as snapshotRegistry,
  snapshotVersion,
} from "@velloo/shadcn-snapshot";
import { readManifest } from "./manifest.ts";

/**
 * Build the `shadcn-upstream` ComponentProvider.
 *
 * Sprint Z's shape — pragmatic hybrid:
 *
 *  - **User-visible win**: components in the user's app are vanilla
 *    shadcn fetched at a pinned version (deposited by the fetcher
 *    into the chosen `componentsPath` directory).
 *  - **Canvas runtime**: still uses the `@velloo/shadcn-snapshot`
 *    registry. The snapshot's canvas-safe overlays already implement
 *    the adapter contract; the rest of the snapshot's components are
 *    near-byte-identical to upstream. Reusing the snapshot registry
 *    avoids bundling 25+ `@radix-ui/*` sub-packages into the velloo
 *    binary — a real cost the bundler-based architecture would carry.
 *  - **Tailwind JIT**: scans the fetched directory so user
 *    customizations to the on-disk files contribute to compiled CSS.
 *  - **Manifest**: prefers the per-cache `manifest.json` (generated by
 *    the fetcher against the fetched .tsx) so the inspector surfaces
 *    upstream prop schemas. Falls back to the snapshot's manifest when
 *    the cache is missing (e.g. during in-memory tests).
 *
 * The deferred bundler-based canvas-from-upstream story is parked for
 * a future sprint (see `docs/decisions.md` #25 + Sprint Z notes).
 */
export interface CreateUpstreamProviderOptions {
  /**
   * Cache directory where fetched components live, e.g.
   * `~/.velloo/providers/shadcn-upstream@2026.05.26/` or a
   * user-app path like `../apps/web/src/components/`. The provider
   * uses this for componentsDir and the manifest source.
   */
  cacheDir?: string;
  /** Version string for the provider's `version` field — defaults to the snapshot's date. */
  version?: string;
}

export function createProvider(opts: CreateUpstreamProviderOptions = {}): ComponentProvider {
  const cacheDir = opts.cacheDir;
  const componentsDir =
    cacheDir && existsSync(join(cacheDir, "ui")) ? join(cacheDir, "ui") : snapshotComponentsDir;
  const version = opts.version ?? snapshotVersion;
  return {
    id: "shadcn-upstream",
    version,
    componentsDir,
    styleEntryPath: snapshotEntryCssPath,
    registry: snapshotRegistry,
    loadManifest: async (): Promise<Manifest> => {
      if (cacheDir && existsSync(join(cacheDir, "manifest.json"))) {
        return await readManifest(cacheDir);
      }
      // Fall back to the snapshot's manifest if no cache was generated
      // (in-process tests, dev shortcuts).
      const { loadManifest } = await import("@velloo/shadcn-snapshot");
      return loadManifest();
    },
    label: `shadcn (upstream @ ${version})`,
  };
}
