import { readFile, stat } from "node:fs/promises";
import { basename, dirname, join, relative, sep } from "node:path";
import { scanReactRouter } from "./react-router.ts";
import { idFromRoutePath, nameFromRoutePath } from "./route-names.ts";
import { scanServerRoutes } from "./server-routes.ts";
import type { Framework, ScannedRoute, ScanResult } from "./types.ts";
import { dirExists, walkFiles } from "./walk.ts";

/** A path under a routes dir, `/`-separated whatever the platform — routes are URLs. */
function routeRelative(from: string, to: string): string {
  return relative(from, to).split(sep).join("/");
}

const PAGE_EXTS = new Set([".tsx", ".ts", ".jsx", ".js"]);

function hasExt(file: string): boolean {
  const dot = file.lastIndexOf(".");
  if (dot === -1) return false;
  return PAGE_EXTS.has(file.slice(dot));
}

function stripExt(file: string): string {
  const dot = file.lastIndexOf(".");
  return dot === -1 ? file : file.slice(0, dot);
}

async function fileExists(path: string): Promise<boolean> {
  const s = await stat(path).catch(() => null);
  return s?.isFile() ?? false;
}

/**
 * A plain Vite SPA has one browser entry rather than a route directory. Treat
 * that entry as the root route so `velloo init --start=scan` has a real screen
 * to hand to the agent instead of degrading to an empty folder. Requiring
 * `index.html` keeps Vite-powered libraries from being mistaken for apps.
 *
 * Prefer the module script declared by index.html; conventional main/index
 * entry names are a fallback for HTML generated by plugins or templates whose
 * attributes our intentionally small parser does not recognize.
 */
async function scanViteSpaRoot(appRoot: string): Promise<ScannedRoute[]> {
  const htmlPath = join(appRoot, "index.html");
  if (!(await fileExists(htmlPath))) return [];

  const candidates: string[] = [];
  try {
    const html = await readFile(htmlPath, "utf8");
    for (const tag of html.matchAll(/<script\b[^>]*>/gi)) {
      const source = tag[0];
      if (!/\btype\s*=\s*["']module["']/i.test(source)) continue;
      const src = source.match(/\bsrc\s*=\s*["']([^"']+)["']/i)?.[1];
      if (!src || /^(?:https?:)?\/\//i.test(src)) continue;
      candidates.push(src.replace(/^\.?\//, ""));
    }
  } catch {
    // The conventional candidates below still make this best-effort.
  }

  candidates.push(
    "src/main.tsx",
    "src/main.ts",
    "src/main.jsx",
    "src/main.js",
    "src/index.tsx",
    "src/index.ts",
    "src/index.jsx",
    "src/index.js",
  );
  for (const rel of new Set(candidates)) {
    const sourceFile = join(appRoot, rel);
    if (await fileExists(sourceFile)) {
      return [{ id: "index", name: "Home", routePath: "/", sourceFile }];
    }
  }
  return [];
}

/**
 * Walk Next.js's app router (`app/<route>/page.*`). Skips `route.*`
 * handlers, layouts, and not-found / error files — only `page.*` files
 * map to a renderable route.
 */
async function scanNextApp(appDir: string): Promise<ScannedRoute[]> {
  const out: ScannedRoute[] = [];
  for await (const file of walkFiles(appDir)) {
    const base = basename(file);
    const stem = stripExt(base);
    if (stem !== "page" || !hasExt(base)) continue;
    const rel = routeRelative(appDir, dirname(file));
    // Convert "settings/(account)/profile" → "settings/profile" by
    // dropping Next's grouping parens. They don't change the URL.
    const routePath =
      `/${rel
        .split("/")
        .filter((s) => !s.startsWith("("))
        .join("/")}`.replace(/\/$/, "") || "/";
    const id = idFromRoutePath(routePath);
    out.push({
      id,
      name: nameFromRoutePath(routePath),
      routePath,
      sourceFile: file,
    });
  }
  return dedupe(out);
}

/**
 * Walk Next.js's pages router (`pages/<route>.*` or `pages/<route>/index.*`).
 * Skips `_app`, `_document`, `_error`, and API routes.
 */
async function scanNextPages(pagesDir: string): Promise<ScannedRoute[]> {
  const out: ScannedRoute[] = [];
  for await (const file of walkFiles(pagesDir)) {
    if (!hasExt(file)) continue;
    const base = basename(file);
    const stem = stripExt(base);
    if (stem.startsWith("_")) continue;
    const rel = routeRelative(pagesDir, file);
    if (rel.startsWith("api/") || rel === "api") continue;
    const segments = rel.split("/");
    const last = stripExt(segments.pop() ?? "");
    const path = last === "index" ? segments : [...segments, last];
    const routePath = path.length === 0 ? "/" : `/${path.join("/")}`;
    out.push({
      id: idFromRoutePath(routePath),
      name: nameFromRoutePath(routePath),
      routePath,
      sourceFile: file,
    });
  }
  return dedupe(out);
}

/**
 * Generic fallback for Vite / React Router / Astro / Nuxt — walk
 * `src/pages/`, `src/routes/`, or `pages/` and treat each file as a
 * route. Astro, Nuxt (`.vue`, bracket params), and
 * Vite-with-filesystem-router all follow this convention closely
 * enough to share one implementation.
 */
async function scanGenericPagesDir(dir: string): Promise<ScannedRoute[]> {
  const out: ScannedRoute[] = [];
  for await (const file of walkFiles(dir)) {
    if (
      !hasExt(file) &&
      !file.endsWith(".astro") &&
      !file.endsWith(".vue") &&
      !file.endsWith(".svelte")
    )
      continue;
    const base = basename(file);
    if (base.startsWith("_")) continue;
    const rel = routeRelative(dir, file);
    const segments = rel.split("/");
    const last = stripExt(segments.pop() ?? "");
    const path = last === "index" ? segments : [...segments, last];
    const routePath = path.length === 0 ? "/" : `/${path.join("/")}`;
    out.push({
      id: idFromRoutePath(routePath),
      name: nameFromRoutePath(routePath),
      routePath,
      sourceFile: file,
    });
  }
  return dedupe(out);
}

/**
 * Walk a SvelteKit routes dir (`src/routes`). Only `+page.svelte` files are
 * pages — the route is the *directory* path, so `+layout` / `+error` /
 * `+page.server.ts` siblings never match. Route groups `(app)` drop out of
 * the URL; `[param]` directories already use the bracket convention the
 * id/name logic understands.
 */
async function scanSvelteKit(dir: string): Promise<ScannedRoute[]> {
  const out: ScannedRoute[] = [];
  for await (const file of walkFiles(dir)) {
    if (basename(file) !== "+page.svelte") continue;
    const rel = routeRelative(dir, dirname(file));
    const segments = rel === "" ? [] : rel.split("/").filter((s) => !/^\(.*\)$/.test(s));
    const routePath = segments.length === 0 ? "/" : `/${segments.join("/")}`;
    out.push({
      id: idFromRoutePath(routePath),
      name: nameFromRoutePath(routePath),
      routePath,
      sourceFile: file,
    });
  }
  return dedupe(out);
}

/** Map one TanStack path segment: `$id` → `[id]`, splat `$` → `[splat]`. */
function tanstackSegment(seg: string): string {
  if (seg === "$") return "[splat]";
  if (seg.startsWith("$")) return `[${seg.slice(1)}]`;
  return seg;
}

/**
 * Walk a TanStack Router file-based routes dir (`src/routes`). Unlike the
 * generic walker, this understands the conventions so layouts and grouping
 * don't leak into the screen list:
 *   - `__root.*` and `route.*` (layout files) are not pages → skipped.
 *   - pathless layout segments (`_authenticated`) and route groups
 *     (`(auth)`) drop out of the URL.
 *   - `index` collapses to its parent path.
 *   - `$param` → `[param]` (and bare `$` splat → `[splat]`), reusing the
 *     same id/name logic as the bracketed Next.js dynamic segments.
 *   - both directory (`a/b.tsx`) and flat-dotted (`a.b.tsx`) nesting map to
 *     the same path; `.lazy` siblings and `routeTree.gen.*` are ignored.
 */
async function scanTanstackRouter(dir: string): Promise<ScannedRoute[]> {
  const out: ScannedRoute[] = [];
  for await (const file of walkFiles(dir)) {
    if (!hasExt(file)) continue;
    let stem = stripExt(routeRelative(dir, file));
    if (stem.endsWith(".lazy")) stem = stem.slice(0, -".lazy".length);
    if (stem === "routeTree" || stem.endsWith(".gen")) continue;

    // TanStack treats both `/` and `.` as nesting separators.
    const raw = stem.split(/[/.]/).filter((s) => s.length > 0);
    const leaf = raw[raw.length - 1];
    if (!leaf) continue;
    // Layout / root files and `-`-prefixed (route-excluded) files aren't pages.
    if (leaf === "__root" || leaf === "route" || leaf.startsWith("_")) continue;
    if (raw.some((s) => s.startsWith("-"))) continue;

    const segments: string[] = [];
    for (const seg of raw) {
      if (seg === "index" || seg === "route") continue; // index collapses to parent
      if (seg.startsWith("_")) continue; // pathless layout
      if (/^\(.*\)$/.test(seg)) continue; // route group
      segments.push(tanstackSegment(seg));
    }
    const routePath = segments.length === 0 ? "/" : `/${segments.join("/")}`;
    out.push({
      id: idFromRoutePath(routePath),
      name: nameFromRoutePath(routePath),
      routePath,
      sourceFile: file,
    });
  }
  return dedupe(out);
}

/** Honor a `tsr.config.json` `routesDirectory` override, if present. */
async function tanstackRoutesDir(appRoot: string): Promise<string | null> {
  try {
    const cfg = JSON.parse(await readFile(join(appRoot, "tsr.config.json"), "utf8")) as {
      routesDirectory?: unknown;
    };
    if (typeof cfg.routesDirectory === "string") return join(appRoot, cfg.routesDirectory);
  } catch {
    // No config (or unreadable) — fall back to the conventional locations.
  }
  return null;
}

/**
 * Keep the first route per id — duplicates surface when both a
 * Next.js app dir and pages dir have the same route, or when a route
 * has both `.tsx` and `.ts` siblings (unusual but possible).
 */
function dedupe(routes: ScannedRoute[]): ScannedRoute[] {
  const seen = new Set<string>();
  const out: ScannedRoute[] = [];
  for (const r of routes) {
    if (seen.has(r.id)) continue;
    seen.add(r.id);
    out.push(r);
  }
  // Sort: index first, then alphabetical. Keeps the generated frames
  // in a predictable order on the board.
  out.sort((a, b) => {
    if (a.id === "index") return -1;
    if (b.id === "index") return 1;
    return a.id.localeCompare(b.id);
  });
  return out;
}

async function readPackageJson(appRoot: string): Promise<Record<string, unknown> | null> {
  try {
    const raw = await readFile(join(appRoot, "package.json"), "utf8");
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    return null;
  }
}

async function detectFramework(appRoot: string): Promise<Framework> {
  const pkg = await readPackageJson(appRoot);
  const deps: Record<string, unknown> = {
    ...((pkg?.dependencies as Record<string, unknown>) ?? {}),
    ...((pkg?.devDependencies as Record<string, unknown>) ?? {}),
  };
  if ("next" in deps) {
    if (await dirExists(join(appRoot, "app"))) return "next-app";
    if (await dirExists(join(appRoot, "src", "app"))) return "next-app";
    if (await dirExists(join(appRoot, "pages"))) return "next-pages";
    if (await dirExists(join(appRoot, "src", "pages"))) return "next-pages";
    return "next-app";
  }
  if ("astro" in deps) return "astro";
  // SvelteKit rides on Vite too — its dedicated conventions must win over
  // the bare-vite fallback.
  if ("@sveltejs/kit" in deps) return "sveltekit";
  if ("nuxt" in deps) return "nuxt";
  // TanStack Router rides on Vite, so check it first — its file conventions
  // (layouts, route groups, pathless segments) need dedicated parsing.
  if (
    "@tanstack/react-router" in deps ||
    "@tanstack/react-start" in deps ||
    "@tanstack/router-plugin" in deps
  ) {
    return "tanstack-router";
  }
  // Config-based React Router (createBrowserRouter / <Routes>) — its route
  // tree lives in code, so a pages-dir walk would surface whatever components
  // happen to live in src/pages/ as fake screens.
  if ("react-router-dom" in deps || "react-router" in deps) return "react-router";
  if ("vite" in deps) return "vite";
  return "unknown";
}

/**
 * Scan a host app for routes. Returns an empty `routes` array when no
 * framework/structure is detected — callers should treat that as "user
 * picked scan but there's nothing to find" rather than an error.
 */
export async function scanAppRoutes(appRoot: string): Promise<ScanResult> {
  const framework = await detectFramework(appRoot);

  if (framework === "next-app") {
    const candidates = [join(appRoot, "src", "app"), join(appRoot, "app")];
    for (const dir of candidates) {
      if (await dirExists(dir)) {
        return { framework, routes: await scanNextApp(dir), routesRoot: dir };
      }
    }
  }
  if (framework === "next-pages") {
    const candidates = [join(appRoot, "src", "pages"), join(appRoot, "pages")];
    for (const dir of candidates) {
      if (await dirExists(dir)) {
        return { framework, routes: await scanNextPages(dir), routesRoot: dir };
      }
    }
  }
  if (framework === "astro") {
    const candidates = [join(appRoot, "src", "pages"), join(appRoot, "pages")];
    for (const dir of candidates) {
      if (await dirExists(dir)) {
        return { framework, routes: await scanGenericPagesDir(dir), routesRoot: dir };
      }
    }
  }
  if (framework === "sveltekit") {
    const dir = join(appRoot, "src", "routes");
    if (await dirExists(dir)) {
      return { framework, routes: await scanSvelteKit(dir), routesRoot: dir };
    }
  }
  if (framework === "nuxt") {
    // Nuxt 4 defaults to `app/pages`; Nuxt 3 to `pages` (or `src/pages` with srcDir).
    const candidates = [
      join(appRoot, "app", "pages"),
      join(appRoot, "src", "pages"),
      join(appRoot, "pages"),
    ];
    for (const dir of candidates) {
      if (await dirExists(dir)) {
        return { framework, routes: await scanGenericPagesDir(dir), routesRoot: dir };
      }
    }
  }
  if (framework === "tanstack-router") {
    const candidates = [
      await tanstackRoutesDir(appRoot),
      join(appRoot, "src", "routes"),
      join(appRoot, "routes"),
    ];
    for (const dir of candidates) {
      if (dir && (await dirExists(dir))) {
        return { framework, routes: await scanTanstackRouter(dir), routesRoot: dir };
      }
    }
  }
  if (framework === "react-router") {
    const result = await scanReactRouter(appRoot);
    if (result && result.routes.length > 0) return result;
    // No parsable router config — fall through to the generic dir walk.
  }

  // Vite or unknown: try common patterns.
  for (const dir of [
    join(appRoot, "src", "routes"),
    join(appRoot, "src", "pages"),
    join(appRoot, "src", "views"),
    join(appRoot, "pages"),
  ]) {
    if (await dirExists(dir)) {
      return {
        framework: framework === "unknown" ? "unknown" : framework,
        routes: await scanGenericPagesDir(dir),
        routesRoot: dir,
      };
    }
  }

  if (framework === "vite") {
    const routes = await scanViteSpaRoot(appRoot);
    if (routes.length > 0) return { framework, routes, routesRoot: appRoot };
  }

  // No JS framework structure — the app may be server-rendered (Django /
  // Flask / Rails / Laravel). Best-effort route extraction from the server
  // router; the placeholder screens don't care what renders the real page.
  const server = await scanServerRoutes(appRoot);
  if (server) return server;

  return { framework, routes: [], routesRoot: appRoot };
}

/**
 * Dependencies marking a directory as a UI app worth scanning for routes.
 * Broader than React on purpose: scan only extracts route *shape* — the
 * placeholders are rebuilt from velloo's own components — so SvelteKit /
 * Nuxt apps scan just as well.
 */
const UI_DEPS = ["react", "next", "astro", "@sveltejs/kit", "svelte", "nuxt", "vue"];

/** True when the directory looks like a UI app worth scanning. */
export async function looksLikeUiApp(appRoot: string): Promise<boolean> {
  const pkg = await readPackageJson(appRoot);
  if (!pkg) return false;
  const deps: Record<string, unknown> = {
    ...((pkg.dependencies as Record<string, unknown>) ?? {}),
    ...((pkg.devDependencies as Record<string, unknown>) ?? {}),
  };
  return UI_DEPS.some((d) => d in deps);
}
